### ISSUE TITLE
Reverse route order conflicting with footprints

### ISSUE THREAD

**Issue by anthonmanix** [trailsjs/trailpack-express#31]
I have a problem when I try to add a wildcard route. I looked at the source an saw that the route order is reversed in first line. This has an effect on footprints which come after routes because of this.

I don't think the routes should be reversed. It is confusing because of the express conventions where order of routes maters.

**Comment by jaumard** [comment]
I revert routes because of this : 

- Create new trails app with express/footprints
- Create a user model
- Call /api/v1/default/info (works)
- Call /api/v1/user (works)

Now remove the reverse : 
- Call /api/v1/default/info (not working anymore)
- Call /api/v1/user (works)

**Comment by anthonmanix** [comment]
I see the problem. Because footprints use parameters for models and are handling default as model.

Maybe you could call next() in FootprintController if model does not exist.

**Comment by jaumard** [comment]
Yes that's the problem :/
Your solution may work but that's not the behavior we want ^^ 
If there no model an error should be return and not going to the next middleware. For example with sequelize if the model does not exist it throw an error and the error is return directly to the user

**Comment by jaumard** [comment]
What are you trying to do exactly ?

**Comment by anthonmanix** [comment]
I'm trying to create a route that always returns index.html. For an angular application so I can do routing on the client side.

{ method: 'GET', path: '/*', handler: 'ViewController.index' }

**Comment by jaumard** [comment]
Hum can you try this https://github.com/jaumard/trails-express-gulp-angular-2/blob/master/config/routes.js it's working for me

**Comment by anthonmanix** [comment]
It does not unfortunately. Also it overrides footprints. I changed the default /api/v1 to just /api, so /{action} catches /api. I also want an /auth endpoint and it catches that to. Don't know maybe I'm doing something wrong.

my routes:
{ method: 'GET', path: '/', handler: 'ViewController.index' },
{ method: 'GET', path: '/{action}', handler: 'ViewController.index' },
{ method: 'GET', path: '/partials/{name}', handler: 'ViewController.partials' },
{ method: 'POST', path: '/auth/login', handler: 'AuthController.login' }

**Comment by anthonmanix** [comment]
I'm using this in my ViewController.index

if (/^\/api/.test(req.path)) { return next(); }

as a workaround so it doesn't handle api endpoints

**Comment by jaumard** [comment]
The only way I see to do it "right" is to redefine footprints routes like this : 
```
{
    method: 'GET',
    path: '/*',
    handler: 'ViewController.helloWorld'
  },

  {
    method: 'POST',
    path: '/api/v1/{model}',
    handler: 'FootprintController.create'
  },
  {
    method: 'GET',
    path: '/api/v1/{model}/{id?}',
    handler: 'FootprintController.find'
  },
  {
    method: [ 'PUT', 'PATCH' ],
    path: '/api/v1/{model}/{id?}',
    handler: 'FootprintController.update'
  },
  {
    method: 'DELETE',
    path: '/api/v1/{model}/{id?}',
    handler: 'FootprintController.destroy'
  },
  {
    method: 'POST',
    path: '/api/v1/{parentModel}/{parentId}/{childAttribute}',
    handler: 'FootprintController.createAssociation'
  },
  {
    method: 'GET',
    path: '/api/v1/{parentModel}/{parentId}/{childAttribute}/{childId?}',
    handler: 'FootprintController.findAssociation'
  },
  {
    method: 'PUT',
    path: '/api/v1/{parentModel}/{parentId}/{childAttribute}/{childId?}',
    handler: 'FootprintController.updateAssociation'
  },
  {
    method: 'DELETE',
    path: '/api/v1/{parentModel}/{parentId}/{childAttribute}/{childId?}',
    handler: 'FootprintController.destroyAssociation'
  },

  /**
   * Constrain the DefaultController.info handler to accept only GET requests.
   */
  {
    method: [ 'GET' ],
    path: '/api/v1/default/info',
    handler: 'DefaultController.info'
  }
```
Like this no need to regex test manually

**Comment by anthonmanix** [comment]
I think you're right. There isn't a simple solution for this. You would need to define where to place the footprint routes if you would like to keep the configured routes. But I don't think that would be elegant.

Thanks for your help.

**Comment by jaumard** [comment]
The problem append only if you need some `*` routes, I think in this case redefining the footprints routes like I wrote above is the most easy/cleaner way, but I think this should be written on the doc ^^ 
I ask myself is they have the same problem with hapi (any thoughts @weyj4 @tjwebb ?)

**Comment by jaumard** [comment]
Closing this for now as there no automatic way to fix this.

**Comment by JAertgeerts** [comment]
@jaumard is this still the most elegant solution? Adding all routes?
