### ISSUE TITLE
Multiple policies for  controller are not working

### ISSUE THREAD

**Issue by cesar2064** [trailsjs/trailpack-express#34]
I have a Locale and Auth policies. But only the first policy in the array inside policies.js config is called (Auth.check).

policies.js

```
module.exports = {
  FootprintController:{
    find:["Auth.check", "Locale.parseHeader"],
    create:["Auth.check", "Locale.parseHeader"],
    update:["Auth.check", "Locale.parseHeader"],
    destroy:["Auth.check", "Locale.parseHeader"],
    createAssociation:["Auth.check", "Locale.parseHeader"],
    findAssociation:["Auth.check", "Locale.parseHeader"],
    updateAssociation:["Auth.check", "Locale.parseHeader"],
    destroyAssociation:["Auth.check", "Locale.parseHeader"]
  }
}
```

**Comment by jaumard** [comment]
What append if you set : 

```
module.exports = {
  FootprintController: ["Auth.check", "Locale.parseHeader"]
}
```
Don't think it's a trailpack-express problem, maybe more trailpack-footprints or trailpack-router...

**Comment by cesar2064** [comment]
@jaumard I tried what you remended me, but it has the same results.

**Comment by cesar2064** [comment]
Where should I report the problem?

**Comment by jaumard** [comment]
Do you have time to test with hapi? If you can reproduce then trailpack router is the right place if not here it's ok :)

**Comment by cesar2064** [comment]
Ok let me try. Thanks.

**Comment by cesar2064** [comment]
Hapi doesn'tt send the next function through the policies?

**Comment by jaumard** [comment]
No hapi didn't have next for policies don't remember if you have to do or just call res()

**Comment by cesar2064** [comment]
Ok, hapi seems to work correctly. It runs the both policies.

**Comment by jaumard** [comment]
Hum I'm currently on a project and I just try this : 

```
module.exports: {
      'FootprintController': ['CheckPermissions.checkRoute', 'CheckPermissions.checkModel']
    },
```
And both are call correctly for me are you using last version of trailpack-router/express ?

**Comment by cesar2064** [comment]
My current dependencies:

  "dependencies": {
    "accept-language": "^2.0.16",
    "bcryptjs": "^2.3.0",
    "eslint": "^2.13.1",
    "express": "^5.0.0-alpha.2",
    "lokijs": "^1.3.19",
    "pg": "^4.5.6",
    "trailpack-bootstrap": "^1.0.1",
    "trailpack-core": "^1.0.0",
    "trailpack-express": "^1.0.5",
    "trailpack-footprints": "^1.0.1",
    "trailpack-repl": "^1.0.8",
    "trailpack-router": "^1.0.6",
    "trailpack-sequelize": "^1.0.3",
    "trails": "^1.0.4",
    "trails-controller": "^1.0.0-beta-2",
    "trails-model": "^1.0.0-beta-2",
    "trails-policy": "^1.0.2",
    "trails-service": "^1.0.0-beta-2",
    "winston": "^2.2.0"
  }

**Comment by cesar2064** [comment]
Umm I found the mistake, thanks for your time, was code in the first route. Sorry :(.

**Comment by cesar2064** [comment]
Forgive me for wasting time

**Comment by jaumard** [comment]
no problem glad you make it work :)

**Comment by cesar2064** [comment]
thanks you are very kind.
