### ISSUE TITLE
Find policy for query string

### ISSUE THREAD

**Issue by gutenye** [trailsjs/trailpack-express#40]
In https://github.com/trailsjs/trailpack-express/blob/master/api/policies/FootprintPolicy.js#L34

```
  find(req, res, next) {
    if (req.params.id && !_.isEmpty(req.query)) {
      return res.boom.preconditionFailed(this.__('errors.footprints.find.mutex'))
    }

    next()
  }
```

Got an error in following example

```
GET /users/1?populate=posts
```

This request should be valid

**Comment by jaumard** [comment]
Hi @gutenye what the error ? Also what is your `config/footprints.js` configuration  ?

**Comment by jaumard** [comment]
Hum can you test with a prefix ? Maybe there a problem when there no prefix, I never had a problem like this before the only difference is that I use a prefix. 

Also if your model is called `User` you should call `/user/1?populate=posts` instead, I think plural are not supported yet.

**Comment by gutenye** [comment]
With prefix, it works. 

What is this file https://github.com/trailsjs/trailpack-express/blob/master/api/policies/FootprintPolicy.js#L34 for?

**Comment by jaumard** [comment]
@gutenye ho I see the problem you're right we should test if `criteria` is not empty and not `query` ! I'll fix this soon! 
I can replicate your problem it work great with or without prefix for me if I didn't set `?populate=post` but once I set it I have the 412 error.

**Comment by jaumard** [comment]
@gutenye I just create a PR with the fix, can you test it and let me know if it's fix your problem ? Normally it should. 

Thanks
