### ISSUE TITLE
Static assets configuration not working

### ISSUE THREAD

**Issue by nyur321** [trailsjs/trailpack-express#43]
I've tried to implement the static configuration on "main.js" and what was said on the documentation which is:

paths: {
        root: path.resolve(__dirname, '..'),
        temp: path.resolve(__dirname, '..', '.tmp'),
        www: path.resolve(__dirname, '..','static'),
    }

but still it's not working. I also have this configuration on middlewares in web.js

middlewares: {
        order: [
            'addMethods',
            'cookieParser',
            'session',
            'passportInit',
            'passportSession',
            'bodyParser',
            'methodOverride',
            'www',
            'router',
            '404',
            '500'
        ],
    },

What I'm doing as a workaround is setting a route to my static directory

{
        method:['GET'],
        path:'/static',
        handler:{
            directory:{
                path:'static'
            }
        }   
    }

Also I'm on windows and I already updated all my packages, Any fixes on the configuration without doing the workaround or did I missed on some configuration?

**Comment by jaumard** [comment]
Hi @nyur321 

If your files look like : 

📁 static 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;myfile.js

When you use the `www` path, you should call `/myfile.js` because `www` offer static files from `/`.
If you use like you use : 
```
{
  method:['GET'],
  path:'/static',
  handler:{
  directory:{
    path:'static'
  }
}
```
Then yes you can use `/static/myfile.js`. 

Do you try this way or do you try to call `/static/myfile.js` with `www` witch return a 404.

**Comment by nyur321** [comment]
I call it this way on my browser http://localhost:3000/static/js/main.js
and I'm using the www option in paths object on config/main.js

This is my folder structure 
![static](https://cloud.githubusercontent.com/assets/11658935/17659184/832be37e-6303-11e6-8681-48b07437eddd.PNG)

which returns with a 404

**Comment by jaumard** [comment]
Witch is the normal behavior :) with the `www` you should call `http://localhost:3000/js/main.js` or use like you did 
```
{
  method:['GET'],
  path:'/static',
  handler:{
  directory:{
    path:'static'
  }
}
```
If you want to use the `www` and have `/static` in your URL you have to set the `www` without `/static`. Generally I do something like : 

📁 public 
&nbsp;&nbsp;&nbsp;&nbsp;📁 static   

And set `www : path.resolve(__dirname, '..','public'),`

**Comment by nyur321** [comment]
Oh I see... Thank you very much. My bad. I'm really interested in trails js and I'm looking forward to this project. Appreciate the good community support.

**Comment by jaumard** [comment]
No problem at all ! Don't hesitate to join us on gitter :) for any problem or share experiences with us
