### ISSUE TITLE
Won't bind to web process on Heroku

### ISSUE THREAD

**Issue by JAertgeerts** [trailsjs/trailpack-express#53]
Because we set host in listen, heroku will not be able to bind the app.
Host must be omitted when deploying to heroku (not even env vars work / have this context).

**Comment by jaumard** [comment]
Some other users manage to make it work on heroku, maybe you should ask on the gitter channel to see how they config this.

**Comment by JAertgeerts** [comment]
Setting host: undefined works.

**Comment by jaumard** [comment]
`0.0.0.0` should be the correct value :)

**Comment by JAertgeerts** [comment]
Thanks @jaumard !
